version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/laravel/Dockerfile
    container_name: br-backend
    restart: always
    volumes:
      - ./:/var/www/br
      - ./docker/laravel/php.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db
    networks:
      - default_network

  db:
    image: mysql:9.3.0
    container_name: br-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buy-rent
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default_network

  nginx:
    image: nginx:1.27.5-alpine
    container_name: br-nginx
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/logs:/var/log/nginx/
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - default_network

  redis:
    restart: always
    image: redis:7.2-alpine
    container_name: br-redis
    volumes:
      - redis_data:/data
    networks:
      - default_network
    ports:
      - "6379:6379"

networks:
  default_network:
    driver: bridge

volumes:
    mysql_data:
    redis_data:
